version: "3"

services:
  app:
    build: .
    container_name: airline-ticket-system
    ports:
      - 8000:8000
    environment:
      MYSQLHOST: mysqldb
      MYSQLUSER: root
      MYSQLPASSWORD: root
      MYSQLDATABASE: airline
    depends_on:
      - mysqldb
    volumes:
      - .:/app

  mysqldb:
    image: mysql:8.0.33
    restart: always
    ports:
      - 9999:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: airline
    volumes:
      - ./airline/init_db:/docker-entrypoint-initdb.d
