version: "3"

services:
  app:
    build: .
    container_name: airline-ticket-system
    ports:
      - 8000:8000
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: airline
    depends_on:
      - mysqldb
    volumes:
      - .:/app

  mysqldb:
    image: mysql:8.0.33
    restart: always
    ports:
      - 9999:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: airline
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config:
